name: Scorecard
on:
  push:
    branches: [main]
  schedule:
    - cron: '17 3 * * 6'
permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  analysis:
    uses: KooshaPari/phenotype-shared/.github/workflows/reusable-scorecard.yml@55c73400a5304b4cebda56083b159b1ffec46a82
    with:
      publish_results: true
