name: Scorecard
on:
  push:
    branches: [main]
  schedule:
    - cron: '17 3 * * 6'
permissions: read-all
jobs:
  analysis:
    uses: KooshaPari/phenotype-shared/.github/workflows/reusable-scorecard.yml@58a298df8b37765e3d04ff975de22d3dd88bfbd9
    with:
      publish_results: true
