name: Scorecard
on:
  push:
    branches: [main]
  schedule:
    - cron: '17 3 * * 6'
permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  analysis:
    uses: KooshaPari/phenotype-shared/.github/workflows/reusable-scorecard.yml@5f4647ef79f620f17b925070155827f3248daaa2
    with:
      publish_results: true
